# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_UNIPHIER) += \
	uniphier-ld11-global.dtb \
	uniphier-ld11-ref.dtb \
	uniphier-ld20-global.dtb \
	uniphier-ld20-ref.dtb \
	uniphier-pxs3-ref.dtb
dtb-$(CONFIG_ARCH_MILBEAUT) += \
	milbeaut-m20v-ref.dtb \
	milbeaut-m20v-ref2.dtb \
	milbeaut-karine-vbd-ble-linux.dtb \
	milbeaut-karine-vbd4gb-ble-linux.dtb \
	milbeaut-karine-vbd8gb-ble-linux.dtb \
	milbeaut-karine-vbd.dtb \
	milbeaut-karine-vbd4gb.dtb \
	milbeaut-karine-vbd8gb.dtb
