/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _DT_BINDINGS_RESET_MILBEAUT_M20V_H
#define _DT_BINDINGS_RESET_MILBEAUT_M20V_H

#define M20V_PCIE_RESET_PWR		0
#define M20V_PCIE_RESET_SOFT0		1
#define M20V_PCIE_RESET_SOFT1		2
#define M20V_PCIE_RESET_BIFU0		3
#define M20V_PCIE_RESET_BIFU1		4
#define M20V_PCIE_RESET_CNT0_MODE	5
#define M20V_PCIE_RESET_CNT1_MODE	6
#define M20V_NETSEC_RESET		7
#define M20V_USB_RESET			8
#define M20V_USB_HIF			9
#define M20V_NAND_RESET			10
#define M20V_EMMC_RESET			11
#define M20V_RESET_MAX			12

#endif	/* _DT_BINDINGS_RESET_MILBEAUT_M20V_H */
