/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _DT_BINDINGS_RESET_MILBEAUT_KARINE_H
#define _DT_BINDINGS_RESET_MILBEAUT_KARINE_H

#define KARINE_USB2_RESET			0
#define KARINE_USB3_RESET			1
#define KARINE_USB3_HIF_RESET		2
#define KARINE_PCIE0_RESET_PWR		3
#define KARINE_PCIE1_RESET_PWR		4
#define KARINE_PCIE0_RESET_CNT0		5
#define KARINE_PCIE1_RESET_CNT0		6
#define KARINE_PCIE0_RESET_SOFT		7
#define KARINE_PCIE1_RESET_SOFT		8
#define KARINE_USB2_EHCI_RESET		9
#define KARINE_RESET_MAX			10
#endif	/* _DT_BINDINGS_RESET_MILBEAUT_KARINE_H */
