#
# Makefile for IIO counter devices
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_104_QUAD_8)	+= 104-quad-8.o
obj-$(CONFIG_STM32_LPTIMER_CNT)	+= stm32-lptimer-cnt.o
obj-$(CONFIG_MILBEAUT_UPDOWN_CNT)	+= milbeaut-updown_cnt.o
obj-$(CONFIG_MILBEAUT_TIMER64) += milbeaut-timer64.o
